# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: 'JobLinux'
  displayName: 'Job Linux'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: CmdLine@2
    inputs:
      script: |
        echo Preparando tarea para escribir el texto $(Agent.OS)
        echo "random text $(Agent.Id) $(Agent.Name) $(Agent.OS)" >$(build.artifactstagingdirectory)/ArchivoLinux.txt
        echo Se escribió el texto
    displayName: 'Creando archivo'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Artefactos'
      publishLocation: 'Container'
    displayName: 'Publicando archivos'

- job: 'JobWindows'
  displayName: 'Job Windows'
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: CmdLine@2
    inputs:
      script: |
         echo Preparando tarea para escribir el texto
         echo “random text $(Agent.Id) $(Agent.Name) $(Agent.OS)” >$(build.artifactstagingdirectory)\ArchivoWindows.txt
         echo Se escribió el texto
    displayName: 'Command Line Script'
  - task: PublishBuildArtifacts@1
    displayName: 'Publicando archivos'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Artefactos'


