# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: 'JobCompilacion'
  displayName: 'JobCompilacion'
  pool: 'Default'
  steps:
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet 5.3.1'
    inputs:
      versionSpec: '5.3.1'
      checkLatest: true

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
    enabled: true
  - task: MSBuild@1
    inputs:
      solution: '**/*.sln'
      msbuildLocationMethod: 'location'
      msbuildLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin'
    enabled: true

  - task: VSBuild@1
    displayName: 'Build solution **\*.sln'
    enabled: false

  - task: VSTest@2
    displayName: 'VsTest - testAssemblies'
    inputs:
      testAssemblyVer2: |
        **\*Test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
    enabled: false

  - task: PublishSymbols@2
    displayName: 'Publish symbols path'
    inputs:
      PublishSymbols: false

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      TargetFolder: '$(build.artifactstagingdirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: '$(Parameters.ArtifactName)'
    condition: succeededOrFailed()

- job: 'JobWindows'
  displayName: 'Job Windows'
  dependsOn: 'JobCompilacion'
  strategy:
    parallel: 10
  pool: 'Default'
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      buildType: 'current'
      downloadType: 'specific'
      downloadPath: '$(System.ArtifactsDirectory)'

  - task: VisualStudioTestPlatformInstaller@1
    inputs:
      packageFeedSelector: 'nugetOrg'
      versionSelector: 'latestStable'
  - task: VSTest@2
    displayName: 'VsTest - testAssemblies copy'
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*Test*.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.ArtifactsDirectory)'
      vsTestVersion: 'toolsInstaller'
    enabled: true



